groups:
  - name: xxtg666 # name of the group
    reviewers: 3 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - xxtg666
      - This-is-XiaoDeng
      - chun-awa
